export const HERO_TEAM_MEMBERS = [
  { name: "Pasho Toska", image: "pasho_toska.png" },
  { name: "Ervin Ziko", image: "ervin_ziko.png" },
  { name: "Altin Luli", image: "altin_luli.png" },
  { name: "Erion Domi", image: "erion_domi.png" },
  { name: "Genci Likaj", image: "genci_likaj.png" },
  { name: "Jul Kreshpaj", image: "jul_kreshpaj.png" },
  { name: "Elisabeta Guri", image: "elisabeta_guri.png" },
  { name: "Xhulio Balli", image: "xhulio_balli.png" },
  { name: "Besjana Fixha", image: "besjana_fixha.png" },
  { name: "Erald Plloha", image: "erald_plloha.png" },
  { name: "Arlind Idrizi", image: "arlind_idrizi.png" },
  { name: "Eliana Kryeziu", image: "eliana_kryeziu.png" },
  { name: "Geri Lluga", image: "geri_lluga.png" },
  { name: "Fjona Rira", image: "fjona_rira.png" },
  { name: "Armando Muco", image: "armando_muco.png" },
  { name: "Kejdi Balla", image: "kejdi_balla.png" },
  { name: "Amanda Oshafi", image: "amanda_oshafi.png" },
  { name: "Kejsi Terolli", image: "kejsi_terolli.png" },
  { name: "Vasjan Çupri", image: "vasjan_cupri.png" },
] as const;
